name: BoE MPC Scraper

on:
  schedule:
    # Run daily at 07:00 UTC (before London market open)
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      lookback_days:
        description: 'Days to look back (default 7, use 730 for full backfill)'
        required: false
        default: '7'
      dry_run:
        description: 'Dry run — scrape without scoring'
        required: false
        default: 'false'
        type: boolean
      backfill:
        description: 'Full backfill (Aug 2024 → present)'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml anthropic

      - name: Run BoE Scraper
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LOOKBACK_DAYS: ${{ github.event.inputs.lookback_days || '7' }}
        run: |
          cd scraper
          ARGS=""
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            ARGS="$ARGS --dry-run"
          fi
          if [ "${{ github.event.inputs.backfill }}" = "true" ]; then
            ARGS="$ARGS --backfill"
          fi
          if [ -n "${{ github.event.inputs.lookback_days }}" ]; then
            ARGS="$ARGS --lookback ${{ github.event.inputs.lookback_days }}"
          fi
          python scraper.py $ARGS

      - name: Commit corpus updates
        run: |
          git config user.name "BoE MPC Scraper"
          git config user.email "bot@macrotechnologies.io"
          git add corpus.json scraper/corpus.json scraper/failed_speeches.json 2>/dev/null || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            ENTRIES=$(python3 -c "import json; d=json.load(open('corpus.json')); print(sum(len(v) for v in d.values()))" 2>/dev/null || echo "?")
            git commit -m "BoE corpus: ${ENTRIES} entries [$(date -u +%Y-%m-%d)]"
            git push
          fi
